<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE authors [
        <!ELEMENT authors (name)*>
        <!ELEMENT name (firstname|lastname)*>
        <!ELEMENT firstname (#PCDATA)>
        <!ELEMENT lastname (#PCDATA)>
        ]>
<authors>
    <name>
        <firstname>Larry</firstname>
        <lastname>Brown</lastname>
    </name>
    <name>
        <firstname>Marty</firstname>
        <lastname>Hall</lastname>
    </name>
</authors>